### ISSUE TITLE
Urlencoding issue

### ISSUE THREAD

**Issue by teamwenger** [tijsverkoyen/TwitterOAuth#2]
When posting a new status update, the tweets come in encoded on twitter. For example, tweeting "This is a test!" shows up on twitter as "This+is+a+test%21"

**Comment by tijsverkoyen** [comment]
Hi, can you send me your code? because I ran the testsuite again and I didn't see any problems.

**Comment by teamwenger** [comment]
I see the issue, I took the code from the previous version that urlencoded the msg before posting. I remove it and its fixed.
