### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dmbekker** [tijsverkoyen/TwitterOAuth#3]
Where did the docs go? http://classes.verkoyen.eu/twitter_oauth/docs. redirects to github now where I can't find any docs..

**Comment by tijsverkoyen** [comment]
The docs were generated based on the PHPDoc for each method. So you can find the docs inside the class itself.
Or check https://github.com/tijsverkoyen/TwitterOAuth/blob/master/tests/index.php there is an example for most methods.
